import Head from 'next/head';
import Image from 'next/image';
import Navigation from '../components/Navigation';

export default function Home() {
  return (
    <>
      <Head>
        <title>acnh wiki</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='flex justify-center items-center'>
        <Navigation />
        <video
          className='absolute right-0 top-0 min-w-full min-h-full -z-10 object-cover brightness-25 overflow-hidden'
          autoPlay
          muted
          src={'/demo.mp4'}
        ></video>
      </div>
    </>
  );
}
